### ISSUE TITLE
Question about licensing

### ISSUE THREAD

**Issue by stalkermv** [Maks-Jago/SwiftFoundation#11]
Dear Maks,

I was recently exploring your repository and noticed that it does not contain a license file. As someone who is interested in using some of the code in my library, I would like to ask you to add a license file to the repository.

I am interested in using some code from the SwiftFoundation and SwiftUIKit repositories. 
In particular, I am interested in using some of the extensions and structures that are included in the repository, such as StorableValue and EquatableNoop, as well as some other extensions and code snippets. I would like to add this code to my library I am working on and would like to license it under the MIT license.

Before proceeding, I would like to confirm if the code in these repositories is licensed, and if so, under what license.

If the code is licensed, I would also like to know if I can get a license that will allow me to use parts of the code from these repositories in my own projects.

The code is currently published, but I will remove any parts that do not comply with your license:
https://github.com/stalkermv/HelpersLibrary
https://github.com/stalkermv/SwiftHelpers

Thank you for your time and attention, and I look forward to hearing from you soon.

**Comment by Maks-Jago** [comment]
Hello.

I have added MIT license files to both repos (SwiftFoundation/SwiftUIKit).
You can use them as is.

Thanks.

**Comment by stalkermv** [comment]
Thank you
